import npc0 from '../../public/assets/characters/dynamic/sample013.png';
import npc1 from '../../public/assets/characters/dynamic/sample019.png';
import npc2 from '../../public/assets/characters/dynamic/sample018.png';
import npc3 from '../../public/assets/characters/dynamic/sample017.png';
import npc4 from '../../public/assets/characters/dynamic/sample015.png';
import npc5 from '../../public/assets/characters/dynamic/sample005.png';
import npc6 from '../../public/assets/characters/dynamic/sample003.png';
import npc7 from '../../public/assets/characters/dynamic/sample006.png';
import npc8 from '../../public/assets/characters/dynamic/sample012.png';
import npc9 from '../../public/assets/characters/dynamic/sample051.png';
export const npc = [npc0, npc1, npc2, npc3, npc4, npc5, npc6, npc7, npc8, npc9];
